package net.hycollege.mapper;

import java.util.List;
import net.hycollege.mybatis.domain.Adress;
import net.hycollege.mybatis.domain.AdressExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AdressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @SelectProvider(type=AdressSqlProvider.class, method="countByExample")
    long countByExample(AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @DeleteProvider(type=AdressSqlProvider.class, method="deleteByExample")
    int deleteByExample(AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @Delete({
        "delete from t_adress",
        "where aid = #{aid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @Insert({
        "insert into t_adress (aid, auid, ",
        "username, adress, ",
        "phone)",
        "values (#{aid,jdbcType=VARCHAR}, #{auid,jdbcType=VARCHAR}, ",
        "#{username,jdbcType=VARCHAR}, #{adress,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=CHAR})"
    })
    int insert(Adress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @InsertProvider(type=AdressSqlProvider.class, method="insertSelective")
    int insertSelective(Adress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @SelectProvider(type=AdressSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="aid", property="aid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="auid", property="auid", jdbcType=JdbcType.VARCHAR),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="adress", property="adress", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.CHAR)
    })
    List<Adress> selectByExample(AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @Select({
        "select",
        "aid, auid, username, adress, phone",
        "from t_adress",
        "where aid = #{aid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="aid", property="aid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="auid", property="auid", jdbcType=JdbcType.VARCHAR),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="adress", property="adress", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.CHAR)
    })
    Adress selectByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @UpdateProvider(type=AdressSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Adress record, @Param("example") AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @UpdateProvider(type=AdressSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Adress record, @Param("example") AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @UpdateProvider(type=AdressSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Adress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    @Update({
        "update t_adress",
        "set auid = #{auid,jdbcType=VARCHAR},",
          "username = #{username,jdbcType=VARCHAR},",
          "adress = #{adress,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=CHAR}",
        "where aid = #{aid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Adress record);
}