package net.hycollege.mybatis.domain;

public class Admin extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.uid
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.username
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.password
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.uid
     *
     * @return the value of t_admin.uid
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.uid
     *
     * @param uid the value for t_admin.uid
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.username
     *
     * @return the value of t_admin.username
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.username
     *
     * @param username the value for t_admin.username
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.password
     *
     * @return the value of t_admin.password
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.password
     *
     * @param password the value for t_admin.password
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}