package net.hycollege.mybatis.domain;

public class Adress extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adress.aid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adress.auid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    private String auid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adress.username
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adress.adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    private String adress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adress.phone
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adress.aid
     *
     * @return the value of t_adress.aid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adress.aid
     *
     * @param aid the value for t_adress.aid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adress.auid
     *
     * @return the value of t_adress.auid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public String getAuid() {
        return auid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adress.auid
     *
     * @param auid the value for t_adress.auid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public void setAuid(String auid) {
        this.auid = auid == null ? null : auid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adress.username
     *
     * @return the value of t_adress.username
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adress.username
     *
     * @param username the value for t_adress.username
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adress.adress
     *
     * @return the value of t_adress.adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adress.adress
     *
     * @param adress the value for t_adress.adress
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adress.phone
     *
     * @return the value of t_adress.phone
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adress.phone
     *
     * @param phone the value for t_adress.phone
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}