package net.hycollege.mybatis.domain;

public class Order extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.oid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.uid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.out_trade_no
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.trade_no
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.gmt_payment
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private String gmtPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_amount
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private Float totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.trade_status
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private String tradeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.oid
     *
     * @return the value of t_order.oid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.oid
     *
     * @param oid the value for t_order.oid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.uid
     *
     * @return the value of t_order.uid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.uid
     *
     * @param uid the value for t_order.uid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.out_trade_no
     *
     * @return the value of t_order.out_trade_no
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.out_trade_no
     *
     * @param outTradeNo the value for t_order.out_trade_no
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.trade_no
     *
     * @return the value of t_order.trade_no
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.trade_no
     *
     * @param tradeNo the value for t_order.trade_no
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.gmt_payment
     *
     * @return the value of t_order.gmt_payment
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String getGmtPayment() {
        return gmtPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.gmt_payment
     *
     * @param gmtPayment the value for t_order.gmt_payment
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setGmtPayment(String gmtPayment) {
        this.gmtPayment = gmtPayment == null ? null : gmtPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_amount
     *
     * @return the value of t_order.total_amount
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public Float getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_amount
     *
     * @param totalAmount the value for t_order.total_amount
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setTotalAmount(Float totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.trade_status
     *
     * @return the value of t_order.trade_status
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.trade_status
     *
     * @param tradeStatus the value for t_order.trade_status
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }
}