package net.hycollege.mybatis.domain;

public class OrderProduct extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.opid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private String opid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.oid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.pid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.pnumber
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    private Integer pnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.opid
     *
     * @return the value of t_order_product.opid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.opid
     *
     * @param opid the value for t_order_product.opid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setOpid(String opid) {
        this.opid = opid == null ? null : opid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.oid
     *
     * @return the value of t_order_product.oid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.oid
     *
     * @param oid the value for t_order_product.oid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.pid
     *
     * @return the value of t_order_product.pid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.pid
     *
     * @param pid the value for t_order_product.pid
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.pnumber
     *
     * @return the value of t_order_product.pnumber
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public Integer getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.pnumber
     *
     * @param pnumber the value for t_order_product.pnumber
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public void setPnumber(Integer pnumber) {
        this.pnumber = pnumber;
    }
}