package net.hycollege.mybatis.domain;

public class ProductDesc extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_desc.pdid
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private String pdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_desc.pdesc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private String pdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_desc.pdid
     *
     * @return the value of t_product_desc.pdid
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String getPdid() {
        return pdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_desc.pdid
     *
     * @param pdid the value for t_product_desc.pdid
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setPdid(String pdid) {
        this.pdid = pdid == null ? null : pdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_desc.pdesc
     *
     * @return the value of t_product_desc.pdesc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String getPdesc() {
        return pdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_desc.pdesc
     *
     * @param pdesc the value for t_product_desc.pdesc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setPdesc(String pdesc) {
        this.pdesc = pdesc == null ? null : pdesc.trim();
    }
}