package net.hycollege.mybatis.domain;

public class Product extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.pid
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.picture
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.pname
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.status
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.prices
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    private Float prices;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.pid
     *
     * @return the value of t_product.pid
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.pid
     *
     * @param pid the value for t_product.pid
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.picture
     *
     * @return the value of t_product.picture
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.picture
     *
     * @param picture the value for t_product.picture
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.pname
     *
     * @return the value of t_product.pname
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.pname
     *
     * @param pname the value for t_product.pname
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.status
     *
     * @return the value of t_product.status
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.status
     *
     * @param status the value for t_product.status
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.prices
     *
     * @return the value of t_product.prices
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public Float getPrices() {
        return prices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.prices
     *
     * @param prices the value for t_product.prices
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public void setPrices(Float prices) {
        this.prices = prices;
    }
}