package net.hycollege.mybatis.domain;

public class UserCar extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_car.cid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_car.uid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_car.pid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_car.pnumber
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    private Integer pnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_car.cid
     *
     * @return the value of t_user_car.cid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_car.cid
     *
     * @param cid the value for t_user_car.cid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_car.uid
     *
     * @return the value of t_user_car.uid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_car.uid
     *
     * @param uid the value for t_user_car.uid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_car.pid
     *
     * @return the value of t_user_car.pid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_car.pid
     *
     * @param pid the value for t_user_car.pid
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_car.pnumber
     *
     * @return the value of t_user_car.pnumber
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public Integer getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_car.pnumber
     *
     * @param pnumber the value for t_user_car.pnumber
     *
     * @mbg.generated Wed Dec 25 16:36:25 CST 2019
     */
    public void setPnumber(Integer pnumber) {
        this.pnumber = pnumber;
    }
}