package net.hycollege.portal.mapper;

import java.util.List;
import java.util.Map;
import net.hycollege.mybatis.domain.Adress;
import net.hycollege.mybatis.domain.AdressExample.Criteria;
import net.hycollege.mybatis.domain.AdressExample.Criterion;
import net.hycollege.mybatis.domain.AdressExample;
import org.apache.ibatis.jdbc.SQL;

public class AdressSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String countByExample(AdressExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_adress");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String deleteByExample(AdressExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_adress");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String insertSelective(Adress record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_adress");
        
        if (record.getAid() != null) {
            sql.VALUES("aid", "#{aid,jdbcType=VARCHAR}");
        }
        
        if (record.getAuid() != null) {
            sql.VALUES("auid", "#{auid,jdbcType=VARCHAR}");
        }
        
        if (record.getUsername() != null) {
            sql.VALUES("username", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getAdress() != null) {
            sql.VALUES("adress", "#{adress,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.VALUES("phone", "#{phone,jdbcType=CHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String selectByExample(AdressExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("aid");
        } else {
            sql.SELECT("aid");
        }
        sql.SELECT("auid");
        sql.SELECT("username");
        sql.SELECT("adress");
        sql.SELECT("phone");
        sql.FROM("t_adress");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Adress record = (Adress) parameter.get("record");
        AdressExample example = (AdressExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_adress");
        
        if (record.getAid() != null) {
            sql.SET("aid = #{record.aid,jdbcType=VARCHAR}");
        }
        
        if (record.getAuid() != null) {
            sql.SET("auid = #{record.auid,jdbcType=VARCHAR}");
        }
        
        if (record.getUsername() != null) {
            sql.SET("username = #{record.username,jdbcType=VARCHAR}");
        }
        
        if (record.getAdress() != null) {
            sql.SET("adress = #{record.adress,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.SET("phone = #{record.phone,jdbcType=CHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_adress");
        
        sql.SET("aid = #{record.aid,jdbcType=VARCHAR}");
        sql.SET("auid = #{record.auid,jdbcType=VARCHAR}");
        sql.SET("username = #{record.username,jdbcType=VARCHAR}");
        sql.SET("adress = #{record.adress,jdbcType=VARCHAR}");
        sql.SET("phone = #{record.phone,jdbcType=CHAR}");
        
        AdressExample example = (AdressExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    public String updateByPrimaryKeySelective(Adress record) {
        SQL sql = new SQL();
        sql.UPDATE("t_adress");
        
        if (record.getAuid() != null) {
            sql.SET("auid = #{auid,jdbcType=VARCHAR}");
        }
        
        if (record.getUsername() != null) {
            sql.SET("username = #{username,jdbcType=VARCHAR}");
        }
        
        if (record.getAdress() != null) {
            sql.SET("adress = #{adress,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.SET("phone = #{phone,jdbcType=CHAR}");
        }
        
        sql.WHERE("aid = #{aid,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_adress
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    protected void applyWhere(SQL sql, AdressExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}