package net.hycollege.mapper;

import java.util.List;
import net.hycollege.mybatis.domain.ProductDesc;
import net.hycollege.mybatis.domain.ProductDescExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProductDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @SelectProvider(type=ProductDescSqlProvider.class, method="countByExample")
    long countByExample(ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @DeleteProvider(type=ProductDescSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @Delete({
        "delete from t_product_desc",
        "where pdid = #{pdid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String pdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @Insert({
        "insert into t_product_desc (pdid, pdesc)",
        "values (#{pdid,jdbcType=VARCHAR}, #{pdesc,jdbcType=LONGVARCHAR})"
    })
    int insert(ProductDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @InsertProvider(type=ProductDescSqlProvider.class, method="insertSelective")
    int insertSelective(ProductDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @SelectProvider(type=ProductDescSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="pdid", property="pdid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="pdesc", property="pdesc", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<ProductDesc> selectByExampleWithBLOBs(ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @SelectProvider(type=ProductDescSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="pdid", property="pdid", jdbcType=JdbcType.VARCHAR, id=true)
    })
    List<ProductDesc> selectByExample(ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @Select({
        "select",
        "pdid, pdesc",
        "from t_product_desc",
        "where pdid = #{pdid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="pdid", property="pdid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="pdesc", property="pdesc", jdbcType=JdbcType.LONGVARCHAR)
    })
    ProductDesc selectByPrimaryKey(String pdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @UpdateProvider(type=ProductDescSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ProductDesc record, @Param("example") ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @UpdateProvider(type=ProductDescSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") ProductDesc record, @Param("example") ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @UpdateProvider(type=ProductDescSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ProductDesc record, @Param("example") ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @UpdateProvider(type=ProductDescSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ProductDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_desc
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @Update({
        "update t_product_desc",
        "set pdesc = #{pdesc,jdbcType=LONGVARCHAR}",
        "where pdid = #{pdid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(ProductDesc record);
}