package net.hycollege.product.manage.mapper;

import java.util.List;
import net.hycollege.mybatis.domain.Product;
import net.hycollege.mybatis.domain.ProductExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @SelectProvider(type=ProductSqlProvider.class, method="countByExample")
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @DeleteProvider(type=ProductSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @Delete({
        "delete from t_product",
        "where pid = #{pid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @Insert({
        "insert into t_product (pid, picture, ",
        "pname, status, prices)",
        "values (#{pid,jdbcType=VARCHAR}, #{picture,jdbcType=VARCHAR}, ",
        "#{pname,jdbcType=VARCHAR}, #{status,jdbcType=CHAR}, #{prices,jdbcType=REAL})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @InsertProvider(type=ProductSqlProvider.class, method="insertSelective")
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @SelectProvider(type=ProductSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="pid", property="pid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="pname", property="pname", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="prices", property="prices", jdbcType=JdbcType.REAL)
    })
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @Select({
        "select",
        "pid, picture, pname, status, prices",
        "from t_product",
        "where pid = #{pid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="pid", property="pid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="pname", property="pname", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="prices", property="prices", jdbcType=JdbcType.REAL)
    })
    Product selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Fri Nov 08 16:14:17 CST 2019
     */
    @Update({
        "update t_product",
        "set picture = #{picture,jdbcType=VARCHAR},",
          "pname = #{pname,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=CHAR},",
          "prices = #{prices,jdbcType=REAL}",
        "where pid = #{pid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Product record);
}