package net.hycollege.mapper;

import java.util.List;
import java.util.Map;
import net.hycollege.mybatis.domain.OrderProduct;
import net.hycollege.mybatis.domain.OrderProductExample.Criteria;
import net.hycollege.mybatis.domain.OrderProductExample.Criterion;
import net.hycollege.mybatis.domain.OrderProductExample;
import org.apache.ibatis.jdbc.SQL;

public class OrderProductSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String countByExample(OrderProductExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_order_product");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String deleteByExample(OrderProductExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_order_product");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String insertSelective(OrderProduct record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_order_product");
        
        if (record.getOpid() != null) {
            sql.VALUES("opid", "#{opid,jdbcType=VARCHAR}");
        }
        
        if (record.getOid() != null) {
            sql.VALUES("oid", "#{oid,jdbcType=VARCHAR}");
        }
        
        if (record.getPid() != null) {
            sql.VALUES("pid", "#{pid,jdbcType=VARCHAR}");
        }
        
        if (record.getPnumber() != null) {
            sql.VALUES("pnumber", "#{pnumber,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String selectByExample(OrderProductExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("opid");
        } else {
            sql.SELECT("opid");
        }
        sql.SELECT("oid");
        sql.SELECT("pid");
        sql.SELECT("pnumber");
        sql.FROM("t_order_product");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        OrderProduct record = (OrderProduct) parameter.get("record");
        OrderProductExample example = (OrderProductExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_order_product");
        
        if (record.getOpid() != null) {
            sql.SET("opid = #{record.opid,jdbcType=VARCHAR}");
        }
        
        if (record.getOid() != null) {
            sql.SET("oid = #{record.oid,jdbcType=VARCHAR}");
        }
        
        if (record.getPid() != null) {
            sql.SET("pid = #{record.pid,jdbcType=VARCHAR}");
        }
        
        if (record.getPnumber() != null) {
            sql.SET("pnumber = #{record.pnumber,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_order_product");
        
        sql.SET("opid = #{record.opid,jdbcType=VARCHAR}");
        sql.SET("oid = #{record.oid,jdbcType=VARCHAR}");
        sql.SET("pid = #{record.pid,jdbcType=VARCHAR}");
        sql.SET("pnumber = #{record.pnumber,jdbcType=INTEGER}");
        
        OrderProductExample example = (OrderProductExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    public String updateByPrimaryKeySelective(OrderProduct record) {
        SQL sql = new SQL();
        sql.UPDATE("t_order_product");
        
        if (record.getOid() != null) {
            sql.SET("oid = #{oid,jdbcType=VARCHAR}");
        }
        
        if (record.getPid() != null) {
            sql.SET("pid = #{pid,jdbcType=VARCHAR}");
        }
        
        if (record.getPnumber() != null) {
            sql.SET("pnumber = #{pnumber,jdbcType=INTEGER}");
        }
        
        sql.WHERE("opid = #{opid,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    protected void applyWhere(SQL sql, OrderProductExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}