package net.hycollege.mapper;

import java.util.List;
import net.hycollege.mybatis.domain.Order;
import net.hycollege.mybatis.domain.OrderExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @SelectProvider(type=OrderSqlProvider.class, method="countByExample")
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @DeleteProvider(type=OrderSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @Delete({
        "delete from t_order",
        "where oid = #{oid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @Insert({
        "insert into t_order (oid, uid, ",
        "out_trade_no, trade_no, ",
        "gmt_payment, total_amount, ",
        "trade_status)",
        "values (#{oid,jdbcType=VARCHAR}, #{uid,jdbcType=VARCHAR}, ",
        "#{outTradeNo,jdbcType=VARCHAR}, #{tradeNo,jdbcType=VARCHAR}, ",
        "#{gmtPayment,jdbcType=VARCHAR}, #{totalAmount,jdbcType=REAL}, ",
        "#{tradeStatus,jdbcType=VARCHAR})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @InsertProvider(type=OrderSqlProvider.class, method="insertSelective")
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @SelectProvider(type=OrderSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="oid", property="oid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="uid", property="uid", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_trade_no", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_no", property="tradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_payment", property="gmtPayment", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.REAL),
        @Result(column="trade_status", property="tradeStatus", jdbcType=JdbcType.VARCHAR)
    })
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @Select({
        "select",
        "oid, uid, out_trade_no, trade_no, gmt_payment, total_amount, trade_status",
        "from t_order",
        "where oid = #{oid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="oid", property="oid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="uid", property="uid", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_trade_no", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_no", property="tradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_payment", property="gmtPayment", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.REAL),
        @Result(column="trade_status", property="tradeStatus", jdbcType=JdbcType.VARCHAR)
    })
    Order selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @Update({
        "update t_order",
        "set uid = #{uid,jdbcType=VARCHAR},",
          "out_trade_no = #{outTradeNo,jdbcType=VARCHAR},",
          "trade_no = #{tradeNo,jdbcType=VARCHAR},",
          "gmt_payment = #{gmtPayment,jdbcType=VARCHAR},",
          "total_amount = #{totalAmount,jdbcType=REAL},",
          "trade_status = #{tradeStatus,jdbcType=VARCHAR}",
        "where oid = #{oid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Order record);
}