package net.hycollege.mapper;

import java.util.List;
import net.hycollege.mybatis.domain.OrderProduct;
import net.hycollege.mybatis.domain.OrderProductExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @SelectProvider(type=OrderProductSqlProvider.class, method="countByExample")
    long countByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @DeleteProvider(type=OrderProductSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @Delete({
        "delete from t_order_product",
        "where opid = #{opid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String opid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @Insert({
        "insert into t_order_product (opid, oid, ",
        "pid, pnumber)",
        "values (#{opid,jdbcType=VARCHAR}, #{oid,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=VARCHAR}, #{pnumber,jdbcType=INTEGER})"
    })
    int insert(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @InsertProvider(type=OrderProductSqlProvider.class, method="insertSelective")
    int insertSelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @SelectProvider(type=OrderProductSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="opid", property="opid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="oid", property="oid", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnumber", property="pnumber", jdbcType=JdbcType.INTEGER)
    })
    List<OrderProduct> selectByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @Select({
        "select",
        "opid, oid, pid, pnumber",
        "from t_order_product",
        "where opid = #{opid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="opid", property="opid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="oid", property="oid", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnumber", property="pnumber", jdbcType=JdbcType.INTEGER)
    })
    OrderProduct selectByPrimaryKey(String opid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @UpdateProvider(type=OrderProductSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @UpdateProvider(type=OrderProductSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @UpdateProvider(type=OrderProductSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Fri Jan 03 12:56:08 CST 2020
     */
    @Update({
        "update t_order_product",
        "set oid = #{oid,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=VARCHAR},",
          "pnumber = #{pnumber,jdbcType=INTEGER}",
        "where opid = #{opid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OrderProduct record);
}